### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by ghost** [SJVAir/sjvair.com#1]
Hello,

After running `vagrant up` on my computer (MacBook Pro) hangs up with the message below.  I left it to run overnight and it had the same message this morning.  I tried running `vagrant up` on a different machine (Mac Mini) and I still get the same message.  Do you know how I could fix this?

```
default: Unpacking cloud-init (19.1-1-gbaa47854-0ubuntu1~18.04.1) over (18.5-45-g3554ffe8-0ubuntu1~18.04.1) ...
    default: Package configuration┌──────────────────────┤ Configuring libssl1.1:amd64 ├──────────────────────┐│││ There are services installed on your system which need to be restarted    ││ when certain libraries, such as libpam, libc, and libssl, are upgraded.   ││ Since these restarts may cause interruptions of service for the system,   ││ you will normally be prompted on each upgrade for the list of services    ││ you wish to restart.  You can choose this option to avoid being││ prompted; instead, all necessary restarts will be done for you││ automatically so you can avoid being asked questions on each library││ upgrade.││││ Restart services during package upgrades without asking?││││<Yes><No>│││└───────────────────────────────────────────────────────────────────────────┘
    default: Setting up libnss-systemd:amd64 (237-3ubuntu10.23) ...
    default: Setting up libexpat1:amd64 (2.2.5-3ubuntu0.1) ...
    default: Setting up python3-apt (1.6.4) ...
    default: Processing triggers for mime-support (3.60ubuntu1) ...
    default: Processing triggers for ureadahead (0.100.0-21) ...
    default: Setting up xxd (2:8.0.1453-1ubuntu1.1) ...
    default: Setting up apt-utils (1.6.11) ...
    default: Processing triggers for install-info (6.5.0.dfsg.1-2) ...
    default: Setting up debconf-i18n (1.5.66ubuntu1) ...
    default: Setting up libcurl3-gnutls:amd64 (7.58.0-2ubuntu3.7) ...
    default: Setting up systemd-sysv (237-3ubuntu10.23) ...
    default: Setting up libelf1:amd64 (0.170-0.4ubuntu0.1) ...
    default: Setting up libglib2.0-0:amd64 (2.56.4-0ubuntu0.18.04.3) ...
    default: No schema files found: doing nothing.
    default: Setting up netplan.io (0.97-0ubuntu1~18.04.1) ...
    default: Setting up bzip2 (1.0.6-8.1ubuntu0.1) ...
    default: Setting up libglib2.0-data (2.56.4-0ubuntu0.18.04.3) ...
    default: Setting up python3-debconf (1.5.66ubuntu1) ...
    default: Processing triggers for libc-bin (2.27-3ubuntu1) ...
    default: Setting up udev (237-3ubuntu10.23) ...
    default: update-initramfs: deferring update (trigger activated)
    default: Setting up nplan (0.97-0ubuntu1~18.04.1) ...
    default: Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.3) ...
    default: Checking for services that may need to be restarted...
    default: done.
    default: Checking for services that may need to be restarted...
    default: done.
    default: Checking init scripts...
    default:
```
